from django.conf import settings

YAPJOY_FORUM_TOPICS_PER_PAGE = getattr(settings, 'YAPJOY_FORUM_TOPICS_PER_PAGE', 8)
YAPJOY_FORUM_REPLIES_PER_PAGE = getattr(settings, 'YAPJOY_FORUM_REPLIES_PER_PAGE', 4)
YAPJOY_FORUM_FILTER_PROFANE_WORDS = getattr(settings, 'YAPJOY_FORUM_FILTER_PROFANE_WORDS', True)
